In [5]:
import numpy as NP

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones(3)

array([1., 1., 1.])

In [15]:
np.ones(3)

array([1., 1., 1.])

In [26]:
np.linspace(0,3,434)

array([0.        , 0.00692841, 0.01385681, 0.02078522, 0.02771363,
       0.03464203, 0.04157044, 0.04849885, 0.05542725, 0.06235566,
       0.06928406, 0.07621247, 0.08314088, 0.09006928, 0.09699769,
       0.1039261 , 0.1108545 , 0.11778291, 0.12471132, 0.13163972,
       0.13856813, 0.14549654, 0.15242494, 0.15935335, 0.16628176,
       0.17321016, 0.18013857, 0.18706697, 0.19399538, 0.20092379,
       0.20785219, 0.2147806 , 0.22170901, 0.22863741, 0.23556582,
       0.24249423, 0.24942263, 0.25635104, 0.26327945, 0.27020785,
       0.27713626, 0.28406467, 0.29099307, 0.29792148, 0.30484988,
       0.31177829, 0.3187067 , 0.3256351 , 0.33256351, 0.33949192,
       0.34642032, 0.35334873, 0.36027714, 0.36720554, 0.37413395,
       0.38106236, 0.38799076, 0.39491917, 0.40184758, 0.40877598,
       0.41570439, 0.42263279, 0.4295612 , 0.43648961, 0.44341801,
       0.45034642, 0.45727483, 0.46420323, 0.47113164, 0.47806005,
       0.48498845, 0.49191686, 0.49884527, 0.50577367, 0.51270

In [27]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
np.random.rand(5)

array([0.6796055 , 0.62552774, 0.75035283, 0.6770701 , 0.97182975])

In [36]:
np.random.rand(25,34)

array([[7.71219697e-01, 2.32429837e-01, 4.03641939e-01, 4.44595893e-01,
        6.51171960e-01, 4.19287589e-01, 3.25475778e-01, 2.80762292e-01,
        1.83460883e-01, 5.15834949e-02, 3.42669304e-01, 7.05490723e-01,
        7.02581170e-01, 3.46319032e-01, 8.61208788e-01, 8.75704453e-01,
        7.02995700e-01, 3.10755588e-01, 4.20876676e-01, 5.33200807e-01,
        9.69314690e-01, 7.78481143e-01, 5.75723475e-01, 9.81516439e-01,
        5.66451914e-01, 6.91884543e-01, 5.05966162e-01, 8.92491103e-01,
        3.03490475e-01, 5.64936227e-01, 7.23767814e-02, 8.70595699e-01,
        4.37031930e-02, 8.64898583e-01],
       [4.92647578e-01, 7.11004322e-01, 4.76013691e-01, 4.86768628e-01,
        9.57039027e-01, 3.37335856e-01, 1.33334427e-01, 9.68231818e-01,
        8.17984526e-01, 7.69084475e-01, 9.58981603e-01, 7.42012657e-01,
        1.40778763e-02, 4.33113272e-02, 7.62520044e-01, 3.01096515e-01,
        5.07467946e-01, 3.46261972e-01, 2.61877252e-01, 3.19707640e-01,
        7.32628245e-01,

In [38]:
np.random.randn(10)

array([ 1.00244378,  1.07526018, -1.91529971,  0.29688515,  2.68952974,
        1.74330449,  1.61944759, -1.27886753,  0.82330108,  1.48061144])

In [39]:
np.random.randn(2,3)

array([[ 0.7329041 , -1.41656307, -0.55826278],
       [-0.11875838,  0.18875827,  1.69508481]])

In [49]:
np.random.randint(0,101,33)

array([ 4, 12, 35, 50,  3, 41, 98, 41,  7, 78, 86, 38, 29, 15, 89, 32, 43,
       95, 12, 47, 69, 25, 75, 11, 73, 92, 79, 27, 39, 82, 43, 99, 58])

In [53]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [63]:
arr = np.arange(0,30)

In [66]:
arr.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [67]:
ranarr = np.random.randint(0,101,10)

In [68]:
ranarr.max()

99

In [69]:
ranarr.min()

2

In [72]:
ranarr.argmin()

7

In [71]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [73]:
ranarr.dtype

dtype('int32')

In [74]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [75]:
arr.shape

(30,)

In [76]:
arr = arr.reshape(5,6)

In [77]:
arr.shape

(5, 6)

In [80]:
arr[1]

array([ 6,  7,  8,  9, 10, 11])

In [82]:
arr[1,0]

6

In [83]:
arr[1:3]

array([[ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [86]:
arr[:5]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [91]:
arr[3:]

array([[18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [92]:
arr[0:2] = 100

In [93]:
arr

array([[100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29]])

In [94]:
arr = np.arange(0,11)

In [96]:
slice_of_arr = arr[0:5]

In [97]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [98]:
slice_of_arr[:] = 9

In [99]:
slice_of_arr

array([9, 9, 9, 9, 9])

In [100]:
arr

array([ 9,  9,  9,  9,  9,  5,  6,  7,  8,  9, 10])

In [101]:
arr_cp = arr.copy()

In [102]:
arr_cp[:] = 786

In [103]:
arr_cp


array([786, 786, 786, 786, 786, 786, 786, 786, 786, 786, 786])

In [104]:
arr

array([ 9,  9,  9,  9,  9,  5,  6,  7,  8,  9, 10])