In [2]:
import numpy as np

In [12]:
arr = np.array([[5,30,5], [34,64,2], [34,5,7]])

In [13]:
arr

array([[ 5, 30,  5],
       [34, 64,  2],
       [34,  5,  7]])

In [14]:
arr.shape

(3, 3)

In [19]:
arr[1][0]

34

In [20]:
arr[1,0]

34

In [21]:
arr[:2]

array([[ 5, 30,  5],
       [34, 64,  2]])

In [29]:
arr[:2,1:]

array([[30,  5],
       [64,  2]])

In [30]:
arr = np.arange(1,11)

In [31]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [32]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
bool_arr = arr > 4

In [34]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [40]:
arr[arr<=3]

array([1, 2, 3])